# Auto-generated by start-team.sh — do not edit
SCRIPT_DIR='/Users/basameschot/projects/momo-agents'
STORIES_DIR='/Users/basameschot/projects/momo-agents/stories'
WORKSPACE_DIR='/Users/basameschot/projects/momo-agents/workspace'
DESIGN_FILE='/Users/basameschot/projects/momo-agents/design/--dev-agents.md'
SENTINEL_DIR='/Users/basameschot/projects/momo-agents/.sentinels'
PYTHON='/Users/basameschot/projects/momo-agents/.venv/bin/python'
ANTHROPIC_API_KEY=''
